<div class="container" style="padding-bottom: 200px">
    <div class="row">
        <h2 class="h2 col-xs-12"><?php $this->getPageTitle(); ?></h2>
    </div>
    <div class="row">
        <?php $this->renderView('alerts/_success'); ?>
        <?php $this->renderView('alerts/_errors') ?>
    </div>
   
    <!-- CORPO -->
    <div>
        <div>

            <!-- Welcome -->
            <div id="welcome">
                <h1 class="text-center">Index Inicial</h1>
                <p>
                    Esta é sua primeira pagina. De esta pagina foi aberta, voce esta com todas as 
                    configuracoes corretas e esta pronto para comecar.
                    
              
            </div>
            </div>
        </div>
</div>


           