<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Objetivando</title>

    <link href="/assets/css/style_general.css" rel="stylesheet">
    <link rel="icon" href="/img/objetivando.ico" type="image/x-icon">


</head>
<body>



<div class="container alinhado_ao_centro">
    <div class="jumbotron">
        <img src="/img/logo.png";
             <br>
        <h1>Página não encontrada</h1>
        <p>Por favor, verifique se a URL digitada está correta.</p>
        
        <div class="text-center">
            <a class="btn btn-outline-danger " href="/" id="btn_validar" role="button">
                <span class="glyphicon glyphicon-menu-left" id="span_validar"></span> Voltar ao inicio
            </a>
        </div>
    </div>
</div>

<!-- jQuery (obrigatório para plugins JavaScript do Bootstrap) -->
<script src="/assets/js/jquery.js"></script>
<!-- Inclui todos os plugins compilados (abaixo), ou inclua arquivos separadados se necessário -->
<script src="/assets/js/bootstrap.min.js"></script>
</body>
</html>