<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="shortcut icon" href="/img/objetivando.ico">
    
    <!-- Bootstrap CSS -->
    <link href="/assets/css/style_main.css" rel="stylesheet">
    
    <title><?php echo $this->getPageTitle('|') ?>inicio</title>
</head>
<body>
    
    <!-- Import do Menu -->
    <?php require_once __DIR__ . "/menu_main.phtml" ?>

    <!-- Import do Conteudo principal -->
    <?php $this->content() ?>

    <!-- Import do Rodape -->
    <?php require_once __DIR__ . "/footer.phtml" ?>    
    
    
 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
   
 
    <script type="text/javascript">
                   $('.navTrigger').click(function () {
       $(this).toggleClass('active');
       console.log("Clicked menu");
       $("#mainListDiv").toggleClass("show_list");
       $("#mainListDiv").fadeIn();

        });
   </script>
 
    <!-- Function used to shrink nav bar removing paddings and adding black background -->
    <script>
        $(window).scroll(function() {
            if ($(document).scrollTop() > 50) {
                $('.nav').addClass('affix');
                console.log("OK");
            } else {
                $('.nav').removeClass('affix');
            }
        });
    </script>
    
    <script>
        var $doc = $('html, body');
        $('a').click(function() {
            $doc.animate({
                scrollTop: $( $.attr(this, 'href') ).offset().top - 80
            }, 500);
            return false;
        });
    </script>
    
    </body>
</html>