



<!-- MENU -->
<nav class="nav" >
        <div class="container">
                <div class="logo">
                    <a href="/">
                        <img href="/" src="img/logo.png" alt="some text">
                    </a>
                </div>
                <div id="mainListDiv" class="main_list">
                        <ul class="navlinks">
                                <li><a href="#">Sobre</a></li>
                                <li><a href="#"  >Baixe o app</a></li>
                                <li><a href="#"  >Envio</a></li>
                                <li><a href="#">Contato</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-user"></span> Login</a></li>
                        </ul>
                </div>
                <span class="navTrigger">
                        <i></i>
                        <i></i>
                        <i></i>
                </span>
        </div>
</nav>


<!-- Sessão por cima da imagem base -->
<section class="home">
    <div class="container">
        
    </div>
</section>